### ISSUE TITLE
Newsletter - statistics problem?

### ISSUE THREAD

**Issue by netengine-at** [Ecodev/newsletter#164] opened 2018-08-13 08:43 UTC
**TYPO3 7.6.26
Newsletter 3.3.1
Firefox 61.0.2 (64-Bit)**

Hello,

we have a problem with the statics tab for the _Newsletter-Extension_. It seems there is some sort of JS- Problem. The "Overview" tab is empty and pagination in the "Emails" tab doesn't work.

![newsletter1](https://user-images.githubusercontent.com/9690313/44021066-1ec3f5a6-9ee4-11e8-8fce-503c9d5bda17.png)

![newsletter2](https://user-images.githubusercontent.com/9690313/44021067-1edf1138-9ee4-11e8-8466-5279c1717156.png)

Error in chrome when I click a pagination Link in "Emails" Tab:

![newsletter3](https://user-images.githubusercontent.com/9690313/44021381-ef2c4130-9ee4-11e8-9326-e4ea51b73cbd.png)

Sorry, I know this is not much information... what can I do to help you with the debugging?

Best wishes.

**Comment by PowerKiKi** [comment] 2018-08-14 01:59
Cannot reproduce on Firefox 61, TYPO3 7.6.31, newsletter 3.3.1. This is very far stretched, but maybe you could try upgrading to your TYPO3 to 7.6.31. Otherwise try another browser (Chrome) and/or have a look at the network panel, instead of JavaScript error. Maybe there is a file that could not be served properly ?

**Comment by netengine-at** [comment] 2018-08-14 06:08
Hello Adrien,

- Browsers: tried it on IE, Chrome, Firefox, Opera, same Problem in all. 
- No network problems, all files loaded 200.

I will try updating T3, although I don't think that will help.

Maybe some other extension is interfering, when I have some time I will make a dev-version and disable other extensions, one-by-one.

Thank you.

PS: don't know if this is helpful, when I click pagination I get the following:

![newsletter4](https://user-images.githubusercontent.com/9690313/44074478-0aa97aa4-9f99-11e8-9fb7-61a83f01c655.png)

![newsletter5](https://user-images.githubusercontent.com/9690313/44074479-0ac805a0-9f99-11e8-9500-25df64e5b4f4.png)

**Comment by netengine-at** [comment] 2018-09-20 07:29
Hello Adrien,

TYPO3 7.6.26
Newsletter 3.3.1

We have been having a new issue with the statistcs, in the json responce from TYPO3 we've been getting an fatal error (*). It seems this has to do with the _left join_ you are using in NewsletterRepository.php. Not sure why _exec_SELECTquery (**)_ can't deal with this, if I create the SQL manually with your inputs everything works fine.

(*) > DBAL fatal error: No handler found in handler_getFromTableList() for: 
> \"tx_newsletter_domain_model_link LEFT JOIN tx_newsletter_domain_model_linkopened ON (tx_newsletter_domain_model_linkopened.link = tx_newsletter_domain_model_link.uid)\" 
> (SQL engine parse ERROR: No join field found in parseFromTables()!: near \"(tx_newsletter_domain_model_linkopened.link = tx_n\")


**newsletter/Classes/Domain/Repository/NewsletterRepository.php
Line: 98 - 104**
```
        $this->fillStateDifferences(
            $stateDifferences, 'tx_newsletter_domain_model_link LEFT JOIN tx_newsletter_domain_model_linkopened ON (tx_newsletter_domain_model_linkopened.link = tx_newsletter_domain_model_link.uid)', 'tx_newsletter_domain_model_link.newsletter = ' . $uidNewsletter, [
                'open_time' => ['increment' => 'linkOpenedCount'],
            ]
        );
```
This change in your code works for us:

```
        $this->fillStateDifferences(
            $stateDifferences, 'tx_newsletter_domain_model_link, tx_newsletter_domain_model_linkopened', '(tx_newsletter_domain_model_linkopened.link = tx_newsletter_domain_model_link.uid) AND tx_newsletter_domain_model_link.newsletter = ' . $uidNewsletter, [
                'open_time' => ['increment' => 'linkOpenedCount'],
            ]
        );

```

(**) this is the error that is thrown, don't ask me why
[TYPO3CMS: DatabaseConnection Class Reference](https://api.typo3.org/typo3cms/60/html/class_t_y_p_o3_1_1_c_m_s_1_1_dbal_1_1_database_1_1_database_connection.html#a9ce1e997a296826cd25b307131e5480b)

Best wishes,
Ulf

**Comment by netengine-at** [comment] 2018-09-20 07:55
Hi Adrian,

nearly forgot this, the Problem seem to be in connection with the DBAL Extension...

Database Abstraction Layer 	dbal 	7.6.26 

Best wishes,
Ulf

**Comment by PowerKiKi** [comment] 2018-09-21 08:01
Could you try reverting to the original line and only removing the parenthesis around the ON clause ?

Also next time, please open a new issue if it's a different problem.

**Comment by PowerKiKi** [comment] 2019-02-11 07:55
Cannot reproduce, and no feedback, so closing for now.

**Closed by PowerKiKi** 2019-02-11 07:55 UTC
